### ISSUE TITLE
[1.12] Crash on Startup

### ISSUE THREAD

**Issue by Kris1432** [thiakil/Applied-Energistics-2#11]
- Minecraft Version: 1.12
- AE2 Version: applied-llamagistics-1.12-rv5-alpha-2.jar
- Forge Version: 2405

Cause: Crash on the client.

Crashlog: https://pastebin.com/LsEAMYQX

**Comment by TheLimePixel** [comment]
yup, I get the same

**Comment by JasonKillsUs** [comment]
exactly the same here, probably needs a forge upgrade: 1.12_2406
thanks for looking into it

**Comment by tyra314** [comment]
Use this config file. That includes a small workaround.

https://gist.github.com/tyra314/e2999eeb04b4e78df9790c4bf11e64c3

@thiakil The problem is here: https://github.com/thiakil/Applied-Energistics-2/blob/rv5-1.12/src/main/java/appeng/core/Registration.java#L234
Without setting a biome id for the spatial biome, the "not forced" code path is never executed, resulting in the error in the crash log.

**Comment by ImAK9** [comment]
Got the same one...

**Comment by thiakil** [comment]
@tyra314 That is part of the problem. It means that it waits until post init to force a registration, instead of using the event like it needs to. When an ID is set it won't actually get registered at all, because the way it's hacked in doesn't get called as I didn't add an event for the Biome registry.

**Comment by thiakil** [comment]
New build has been released which should fix this.
