### ISSUE TITLE
Crash with XNET invalid Class Xnet issue?

### ISSUE THREAD

**Issue by tyler489** [thiakil/Applied-Energistics-2#35]
#Playing Beyond the new Frontier 2.7 https://minecraft.curseforge.com/projects/beyond-the-new-frontier/files/2453698 and im getting a crash. I believe someone is pushing power from XNET to an applied llamagistics (the 1.12 fork of ae) crafting cpu

Crash Report
https://pastebin.com/MBJSLUY8
Minecraft Version: 1.12
AE2 Version: Beta 1
Forge Version: 14.21.1.2407

https://github.com/McJty/XNet/issues/139

**Comment by thiakil** [comment]
Something has likely corrupted your world, or otherwise the Crafting tile's `Blockpos pos` member has been changed. It's trying to get its own block and the block at the pos is not a AL one.

**Comment by tyler489** [comment]
XNET is trying to get a class that doesnt exist in your mod atleast according to the server dev

**Comment by thiakil** [comment]
No, that's not what's happening.

**Comment by thiakil** [comment]
What you have is that your save file says the block at that location is a connector, but the tile entity is the crafting block. There is no usual way for this to desync. Could potentially be caused by building/swapping/moving wands though.

You will probably have to use NBTExplorer to delete the TE at that location.
