### ISSUE TITLE
Network Event caused exception when closing server

### ISSUE THREAD

**Issue by FiveEYZ** [thiakil/Applied-Energistics-2#46]
#### Description

After I did a /stop I noticed some exceptions in the log:
http://paste.ubuntu.com/25216218/ (they are in the beginning)

#### Environment
This modpack: https://minecraft.curseforge.com/projects/preedcraft
Windows Server 2012 R2
spongeforge-1.12-2397-7.0.0-BETA-2486

- Minecraft Version: 1.12
- AE2 Version: applied-llamagistics-1.12-rv5-beta-3
- Forge Version: forge-1.12-14.21.1.2428-universal

**Comment by thiakil** [comment]
Could you please try running the world save under a standard forge server (*without* sponge, but with everything else) and let me know if you get the same errors?

It seems to be that when shutting down, the `WorldServer` rejects scheduled task additions. If it is indeed normal behaviour it has simply gone unnoticed as I recently changed the exception handling to print the stack trace instead of only outputting it in debug mode.

**Comment by runescapejon** [comment]
Just tried this using 1.11.2 and i use normal forge server without no sponge just applied-llamagistics-1.11.2-rv5-beta-3 installed nothing else and had no issue's when stopping the server, when i install spongeforge this problem create's this happen with AE2 1.10.2 on the original github and i had report it too spongeforge github just few hours ago not only it give errors in the console in the but it can and it mess up the level.dat and change the block/item id's i haven't seen that in this fork tho but it could happen with this same error

**Comment by thiakil** [comment]
Could you please link the Sponge issue?

**Comment by runescapejon** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1690
