### ISSUE TITLE
Grid Node

### ISSUE THREAD

**Issue by ghost** [thiakil/Applied-Energistics-2#80]
https://gist.github.com/xKnightGamingx/dca04d04f6703648fd1553a5f4171765

Version Latest: applied-llamagistics-1.12.1-rv5-beta-8
Sponge version: spongeforge-1.12.2-2486-7.0.0-BETA-2679

**Comment by thiakil** [comment]
Use the issue template and don't just post part of the crashlog.

**Comment by xKnightGamingx** [comment]
I did not post the whole crash log cause I did not want you guys everyone info about my box/server

**Comment by ghost** [comment]
I updated the crash log, I just don't like given out the whole crash log cause then some mod devs will use it against the person who posts it by blaming them for something breaking

**Comment by thiakil** [comment]
It is unfortunate you seem to have had bad experiences in the past, though the information in that file is useful to track down the problem (and in many cases users don't post the `caused by` lines which is crucial)

Whatever you have connected to the import bus is likely returning a null `ItemStack`, which should never be happening in 1.11+
Unfortunately the Exception is lacking information about the position.

**Comment by ghost** [comment]
Thiakil according to my admin he use the cobble gen, tried first with transfer nodes and it seemed to work without any issues (placed that one in the nether) since it seemed to work I decided to try to put an import on the cobble gen but the only me controller and then it crashed.

**Comment by thiakil** [comment]
@xKnightGamingx if you edit comments like that I don't get a notification. You're lucky I decided to check in on this thread.

That description is also confusing as hell. But still, I'm 99% sure whatever is attached to it is giving a null ItemStack, which it shouldn't be.
