### ISSUE TITLE
Item Sorting Issue

### ISSUE THREAD

**Issue by Timeslice42** [thiakil/Applied-Energistics-2#83]
[rv5-beta-8]
When setting a terminal to sort items by name the lore text is not taken into account. This makes sorting by name useless for items such as enchanted books.

**Comment by thiakil** [comment]
as far as I know, lore is only for the tooltip. The `name` sorter uses the display name.

**Comment by Timeslice42** [comment]
I know - that's the problem. As far as the display name is concerned my me chest is full of hundreds of "Enchanted Book", all using random/default sorting. When determining the sort order it needs to tack on what's in the tooltip so that it can sort them in a meaningful manner. That is to say the comparator should be looking at "Enchanted Book Power II" vs "Enchanted Book Protection III" rather than "Enchanted Book" vs "Enchanted Book". That may mean overloading the comparator.

**Comment by thiakil** [comment]
then it wouldnt be sorting by name, but rather tooltip.

**Comment by Timeslice42** [comment]
No, you don't get it. It needs to sort by `name` + `tooltip`. Even when only considering vanilla minecraft items, merely sorting by name is _not_ unique.

Sorting by `name` + `tooltip` will sort in exactly the same order as the current sort by `name`, except in cases where the difference in the items isn't in the name, but in the tooltip. SUCH AS WITH ENCHANTED BOOKS.

Enchant yourself a good dozen or two enchanteds books and put them in an ME chest. You will clearly see that sorting by name currently leaves them **unsorted**.

**Comment by leagris** [comment]
I see a case for Forge to implement a `compareWith` method into itemStacks, so mods can override that compareWith method with whatever rules are relevant for their specific items. Otherwise it would call a default itemStack compareWith or call-back with some parameters like:
- itemStack to compare with
- array of Compare fields (un/localized name, NBT var name/value...)

Would return -1, 0 or 1 depending of how itemStacks compares.

**Comment by thiakil** [comment]
@leagris an interesting idea, but probably needs a bit more work

@Timeslice42 I see you deleted your comment, but trying to sort with tooltips also *while in name mode* is a bad idea for both performance and logic reasons.

**Comment by Timeslice42** [comment]
The logic wouldn't change at all, and it's a small impact to performance if you only do it when needed.
Just do something like this bit of pseudocode:

```
public static Comparator<ItemStack> ItemStackNameComparator = new Comparator<ItemStack> {
   public int compare(ItemStack item1, ItemStack item2) {
      int result = item1.getDisplayName().compareTo(item2.getDisplayName());
      if (result == 0)
         result = item1.getTooltip().compareTo(item.getTooltip());
      return result;
   }
};
```

This assumes that display names and tooltips are a String, and that inventories are a ``List<ItemStack>``, but if they are, all you do is call ``Collections.sort(inventory, ItemStackNameComparator);``, creating an ArrayList out of ``inventory`` if neccessary.

Since I can't _find_ the AE2 inventory sorting code I can't confirm any of this, but what I've laid out here is simple stuff.

**Comment by thiakil** [comment]
Stop being a dick. The moment you change the comparator, *you are changing the logic*. End of story.

Comparing the tooltip for things where the name is the same is idiotic from a performance perspective. *It also is not comparing by name* on the secondary sort.

Say the user has multiple copper ore from different mods in their system. Your code would compare the tooltip *for absolutely no benefit*.

Your new issue for enchanted books has already been marked as solved in dev.

**Comment by Timeslice42** [comment]
Is this fix going to work for all items that have this issue, or did you make a special case just for enchanted books? I made the other issue for enchanted books because they are a vanilla item, however there are plenty of modded items that have the same problem, such as ancient tomes, seed bags, safari nets, soul vials, soul gems, etc.

You say "changing the logic" as if it is somehow going to now break all sorting by name. I'm telling you the sorting will come out exactly the same, except in the cases where it wasn't sorting correctly to begin with.

Let me give you an equivalent analogy, since this obviously isn't making sense to you. Say you have a list of people that you need to sort by name (i.e. "Smith, John"). Currently you are only sorting by last name. Thus, if you have a group of people with the same last name, they are going to be unsorted. To do it correctly you need to sort by the last name AND the first name. However there is absolutely no reason to sort by the first name if the last name is different.

You only need to compare the tooltips if the display names are the same. You don't even need an additional differentiator if the display names are different. And seriously, how many different "copper ores" do you expect a user to have? I can gaurantee you that doing an additional six compares isn't going to have the crippling impact on performance that you seem to be expecting. The only place where this is going to have an appreciable cost is where additional work actually needs to be done.

I don't even know what you're trying to say with your second sentance. There is no "secondary sort". A comparator is a function which takes two objects and returns one of three integers: a 1 if object a is greater than object b, a 0 if they are equal, or a -1 if object a is less than object b. The comparator itself doesn't do any sorting, it is literally just comparing one thing to another. It's the results of the comparator that a sorting routine uses to decide how to sort things. When and what it decides to do comparisons on is its own business, you just have to ensure that the comparator returns relavent and consistent results.

If we've already established that the display names are the same, we don't need to reestablish that the display names are the same again when we compare the tooltips.

All that said, you *could* compare the displayname and tooltip at the same time by combining them into a single string before doing the string compare, but that would actually be more expensive than doing it in two steps, both purely on a computational level, and where garbage collection/memory fragementation is concerned.

**Comment by thiakil** [comment]
*A tooltip is not a name*. The name sorter is **not** going to sort by tooltip. If you really need to sort the items you mentioned by extra data, name it in an Anvil/Inscriber or ask the relevant dev to add the info to its display name.

I don't care if *some* items have a tooltip that *contains* a name of something else. It does not apply to every case. Take a Battery that lists its charge in the tooltip, that's not going to sort correctly in all cases.

> Let me give you an equivalent analogy, since this obviously isn't making sense to you

A) I know exactly what you're getting at. B) Not equivalent, because again, *a tooltip is not a name*. It would be like sorting by someone's last name, and then by a description of their characteristics.

> I don't even know what you're trying to say with your second sentance.

If you don't know what I mean, *why the fuck do you make the assumption I don't know what a Comparator is?* I know exactly what it does and how to optimise that to only do the secondary comparison when necessary.

A *secondary sort* is the *First Name* in your analogy above. *The second piece of info you use to sort*.

Some things you don't seem to understand

* Tooltips are not a single string, it is a list of strings. *Hello Garbage Collection*
* There is no tooltip cache, so again, garbage collection every time you compare one to the other
* To generate a tooltip an Item must deserialise an *uncertain* amount of NBT data, some of which won't even be used because a difference was already found.
* Again, it must do this every time a comparison is made, discarding any intermediary objects (non-strings)
* To do tooltips *properly* involves firing an event *for each tooltip*, a very expensive operation
* My example of Copper ore was to illustrate where all the calls involved *is redundant because there is no difference*
* Examples you gave such as the Soul Vials & Safari Nets probably involve a lookup in the Entity Registry too.
* If a modded item wants to be sorted based on its content, *it can give that info in the display name*
